FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "-m", "app.main"]
#docker build -t cjs0533/fastapi:v1.1 .
#docker push cjs0533/fastapi:v1.1
